services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./entrypoint.sh:/app/entrypoint.sh
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=mecanizou
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - ENV=DEV
    depends_on:
      - database

  database:
    image: mysql:lts
    ports:
      - 3306:3306
    volumes:
      - ./src/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
