services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./entrypoint.sh:/app/entrypoint.sh
    ports:
      - 3000:3000
    environment:
      - ENV=DEV
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=mecanizou
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis

  database:
    image: mysql:lts
    ports:
      - 3306:3306
    volumes:
      - ./src/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:6.2.14
    ports:
      - 6379:6379

  test:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    environment:
      - ENV=TEST
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=mecanizou_test
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: [ "npm", "run", "test:e2e" ]
    depends_on:
      - database
      - redis
